import type { HospitalInfo } from '@/pages/main/components/HospitalListItem';
import ImgHospital1 from '@/shared/assets/images/ImgHospital1.png';
import ImgHospital2 from '@/shared/assets/images/ImgHospital2.png';
import ImgHospital3 from '@/shared/assets/images/ImgHospital3.png';
import ImgHospital4 from '@/shared/assets/images/ImgHospital4.png';
import ImgHospital5 from '@/shared/assets/images/ImgHospital5.png';
import ImgHospital6 from '@/shared/assets/images/ImgHospital6.png';
import ImgHospital7 from '@/shared/assets/images/ImgHospital7.png';
import ImgHospital8 from '@/shared/assets/images/ImgHospital8.png';

export const dummyHospitals: HospitalInfo[] = [
  {
    id: 1,
    name: '태능성심정신건강의학과의원',
    isOpen: true,
    closeAt: '18:00',
    distance: 14.5,
    address: '서울시 노원구 동일로',
    department: '정신건강의학과',
    review: null,
    image: ImgHospital1,
  },
  {
    id: 2,
    name: '태릉씨티치과의원',
    isOpen: true,
    closeAt: '18:30',
    distance: 14.5,
    address: '서울시 노원구 동일로',
    department: '치과',
    review: null,
    image: ImgHospital2,
  },
  {
    id: 3,
    name: '모아한방병원',
    isOpen: true,
    closeAt: '20:00',
    distance: 14.5,
    address: '서울시 노원구 동일로',
    department: '한방내과',
    review: null,
    image: ImgHospital3,
  },
  {
    id: 4,
    name: '태능성심의원',
    isOpen: true,
    closeAt: '17:00',
    distance: 14.5,
    address: '서울시 노원구 동일로',
    department: '정신건강의학과',
    review: null,
    image: ImgHospital4,
  },
  {
    id: 5,
    name: '참다운요양병원',
    isOpen: null,
    closeAt: '18:00',
    distance: 14.5,
    address: '서울시 노원구 동일로',
    department: '내과',
    review: null,
    image: ImgHospital5,
  },
  {
    id: 6,
    name: '센트럴치과의원',
    isOpen: true,
    closeAt: '21:00',
    distance: 14.5,
    address: '서울시 노원구 동일로',
    department: '치과',
    review: null,
    image: null,
  },
  {
    id: 7,
    name: '방병원',
    isOpen: true,
    closeAt: '17:30',
    distance: 14.6,
    address: '서울시 노원구 동일로',
    department: '내과',
    review: 4.5,
    image: ImgHospital6,
  },
  {
    id: 8,
    name: '청담보드레의원',
    isOpen: null,
    closeAt: '18:30',
    distance: 14.6,
    address: '서울시 노원구 동일로',
    department: '성형외과',
    review: null,
    image: ImgHospital7,
  },
  {
    id: 9,
    name: '홍성환산부인과의원',
    isOpen: true,
    closeAt: '18:30',
    distance: 14.6,
    address: '서울시 노원구 화랑로',
    department: '성형외과',
    review: null,
    image: null,
  },
  {
    id: 10,
    name: '연세사랑병원',
    isOpen: true,
    closeAt: '18:00',
    distance: 14.6,
    address: '서울시 노원구 동일로',
    department: '내과',
    review: null,
    image: ImgHospital8,
  },
];
